name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: Test Build
        run: go build .
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  deploy-main:
    needs:
      - build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: Build main
        run: go build .
      - name: Deploy main
        uses: appleboy/scp-action@main
        with:
          host: 119.23.45.126
          username: xiaoyou
          password: ${{ secrets.MAIN_SSH_KEY }}
          source: "linux_tools"
          target: "linux_tools"

